"""Dated recovery copies kept outside the app and its Git checkout."""
from datetime import datetime, timezone
import os
from pathlib import Path
import uuid

import quote_transfer


def directory():
    configured = os.environ.get("QUOTE_BACKUP_DIR")
    return Path(configured).expanduser().resolve() if configured else Path.home() / "Metro Quote Backups"


def save(job, slug):
    data = quote_transfer.export_quote(job)
    folder = directory()
    folder.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H-%M-%S-%fZ")
    # Slug is generated by the app, never taken from an uploaded filename.
    path = folder / f"{slug[:100]}_{stamp}_{uuid.uuid4().hex[:8]}.metroquote"
    try:
        with path.open("xb") as stream:
            stream.write(data)
    except Exception:
        path.unlink(missing_ok=True)
        raise
    return str(path)
